# -------------------------------------
# Command Line Menu
# -------------------------------------
cli:
  - name: cancel
    url: /docs/cli/pulumi_cancel/
    weight: 1
    parent: commands

  - name: config
    url: /docs/cli/pulumi_config/
    weight: 2
    parent: commands

  - name: console
    url: /docs/cli/pulumi_console/
    weight: 3
    parent: commands

  - name: destroy
    url: /docs/cli/pulumi_destroy/
    weight: 4
    parent: commands

  - name: import
    url: /docs/cli/pulumi_import/
    weight: 5
    parent: commands

  - name: login
    url: /docs/cli/pulumi_login/
    weight: 6
    parent: commands

  - name: logout
    url: /docs/cli/pulumi_logout/
    weight: 7
    parent: commands

  - name: logs
    url: /docs/cli/pulumi_logs/
    weight: 8
    parent: commands

  - name: new
    url: /docs/cli/pulumi_new/
    weight: 9
    parent: commands

  - name: plugin
    url: /docs/cli/pulumi_plugin/
    weight: 10
    parent: commands

  - name: policy
    url: /docs/cli/pulumi_policy/
    weight: 11
    parent: commands

  - name: preview
    url: /docs/cli/pulumi_preview/
    weight: 12
    parent: commands

  - name: refresh
    url: /docs/cli/pulumi_refresh/
    weight: 13
    parent: commands

  - name: stack
    url: /docs/cli/pulumi_stack/
    weight: 14
    parent: commands

  - name: state
    url: /docs/cli/pulumi_state/
    weight: 15
    parent: commands

  - name: up
    url: /docs/cli/pulumi_up/
    weight: 16
    parent: commands

  - name: version
    url: /docs/cli/pulumi_version/
    weight: 17
    parent: commands

  - name: whoami
    url: /docs/cli/pulumi_whoami/
    weight: 18
    parent: commands
