name: Push
on:
  push:
    branches:
      - master
jobs:
  merge:
    name: Create website pull request
    runs-on: ubuntu-18.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.81.0'
          extended: true

      - name: Check out the website
        uses: actions/checkout@v2
        with:
          repository: pulumi/docs
          path: docs
          ref: cnunciato/hugo-modules
          token: ${{ secrets.PULUMI_BOT_TOKEN }}

      - name: Configure Git
        run: |
          git config --global url."https://${{ secrets.PULUMI_BOT_TOKEN }}:x-oauth-basic@github.com/pulumi/pulumi-hugo".insteadOf "https://github.com/pulumi/pulumi-hugo"

      - name: Update the module reference
        working-directory: docs
        run: hugo mod get -u github.com/${{ github.repository }}/themes/current

      - name: Fetch the associated PR
        uses: octokit/request-action@v2.x
        id: pull_requests
        with:
          route: GET /repos/{owner}/{repo}/commits/{commit}/pulls
          owner: pulumi
          repo: pulumi-hugo
          commit: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v3
        with:
          path: docs
          base: cnunciato/hugo-modules
          branch: ${{ github.repository }}/${{ github.sha }}
          author: Pulumi Bot <bot@pulumi.com>
          committer: Pulumi Bot <bot@pulumi.com>
          title: Update ${{ github.repository }}
          commit-message: Update the module reference for ${{ github.repository }}
          token: ${{ secrets.PULUMI_BOT_TOKEN }}
          draft: true
          body: |
            Updates the Hugo module reference for ${{ github.repository }}. See ${{ steps.pull_requests.outputs.data[0].html_url }} for details.
